to_omit = [
    'Oceania Cruises',
    'Cyfrowy Polsat',
    'Wielton',
    'Woseba',
    'Milk Hydrosan sp. z o.o.',
    'Global Foundries',
    'Eurovision',
    'Delta Air Lines',
    'Rabobank',
    'Preem AB',
    'Iberia',
    'Sidley Austin',
    'World Boxing Council',
    'World Boxing Organization',
    'World Boxing Association',
    'International Boxing Federation',
    'BP',
    'Boohoo Group',
    'Air Malta',
    'Twitter',
    'UPS',
    'FedEx',
    'Netflix',
    'Daimler',
    'IOC',
    'UEFA',
    'International Ice Hockey Federation',
    'AerCap',
    'FIFA',
    'ICBC',
    'Equinor',
    'InPost',
    'Pekao SA',
    'PKO BP',
    'PZU SA',
    'GM',
    'MVRDV',
    'Remitly Global',
    'Volvo',
    'NHL',
    'Sandvik',
    'International Cycling Union',
    'World Athletics Council',
    'Grant Thornton',
    'International Skating Union',
    'Uber',
    'Bolt',
    'World Rugby Union',
    'World Rowing Federation',
    'Exxon',
    'International Tennis Federation',
    'Roku',
    'MSC',
    'Alaska Airlines',
    'American Airlines',
    'International Cat Federation',
    'Centrica',
    'Aston Martin',
    'WarnerMedia',
    'Dell',
    'DirecTV',
    'Subaru',
    'Apple',
    'Ford',
    'Boeing',
    'Jaguar',
    'Harley-Davidson',
    'Neste Oyj',
    'Hapag Lloyd',
    'HP Inc.',
    'BNP Paribas',
    'Bosch',
    'Ingram Micro',
    'Farfetch',
    "Women's Tennis Association",
    'Spotify',
    'Asos',
    'MSCI',
    'Alcoa',
    'Comarch',
    'Kinross Gold',
    'Mazda',
    'Canada Goose',
    'Mercedes-Benz',
    'Honda',
    'Oracle',
    'Chipperfield',
    'Valero Energy',
    'Metso Outotec',
    'TSMC',
    'DHL',
    'Airbus',
    'SonoSim',
    'Ponsse PLC',
    'Conformis',
    'Wintershall Dea AG',
    'Trafigura',
    'Siemens',
    'Norsk Hydro',
    'Siemens Energy AG (Independent)',
    'Accenture',
    'Formula One',
    'International Weightlifting Federation',
    'Live Nation Entertainment',
    'Carnival',
    'Intercontinental Exchange',
    'WWE',
    'TJ Maxx',
    'Norwegian Cruise Lines',
    'Asian Infrastructure Investment Bank',
    'Regent Seven Seas Cruises',
    'Autodesk',
    'McKinsey',
    'Monroe Energy',
    'OneWeb',
    'Expedia',
    'Geodis',
    'Assicurazioni Generali',
    'Bose',
    'Haniel',
    'CD Projekt',
    'Grupa Azoty',
    'Atlas Copco',
    'Ikea',
    'Bentley',
    'Intel',
    'Under Armour',
    'DSV A/S',
    'Mango',
    'CMA CGM',
    'Diageo',
    'Skoda',
    'Magna',
    'Marks & Spencer',
    'Alphabet',
    'Volkswagen',
    'Embraer',
    'Nemak',
    'Sabre',
    'Dow',
    'Amadeus IT Group',
    'Activision Blizzard',
    'Acronis',
    'DXC Technology',
    'J Sainsbury',
    'Electronic Arts',
    'EPAM',
    'R&A',
    'BCG',
    'Avid',
    'Par Pacific',
    'Linklaters',
    'Morrisons',
    'World Federation of Exchanges',
    'WPP PLC',
    'State Street',
    'Airbnb',
    'TripAdvisor',
    'Asda',
    'New Development Bank',
    'Swarovski',
    'Netscout',
    'AMD',
    'Adamed',
    'Morgan Advanced Materials',
    'Teknotherm Marine HVAC sp. z o.o.',
    'Bombardier',
    'Bank of China',
    'Lego',
    'Cogent Communications',
    'Panasonic',
    'Louis Dreyfus',
    'Hermes',
    'JD Sports',
    'LVMH',
    'Dassault Aviation',
    'Nokia',
    'Adobe',
    'Kering',
    'Samsung',
    'Hyundai',
    'Canon',
    'Moncler',
    'Confor Step',
    'Henkel',
    'Rockwool',
    'Carmim',
    'OMV',
    "Moody's",
    'Coursera',
    'Mastercard',
    'Inditex',
    'Visa',
    'VMWare',
    'Puma',
    'Paypal',
    'ZHA',
    'Tendam',
    'Esri',
    'KPMG',
    'Radio Free Europe',
    'Coupa',
    'Kearney',
    'Aldi',
    'TikTok',
    'American Express',
    'Burberry',
    'Chanel',
    'Tous',
    'Coinbase',
    'Danone',
    'Fitch',
    'Paulig',
    'PwC',
    'Upwork',
    'Norton Rose Fulbright',
    'Take-Two Interactive',
    'AECOM',
    'Deloitte',
    'Fortinet',
    'United Airlines',
    'Fazer',
    'Vanguard',
    'Dino Polska',
    'Banco Santander SA',
    'CBRE',
    'Komatsu',
    'Levi Strauss',
    'Trimble',
    'Scania',
    'Akamai',
    'Iveco',
    'Wise PLC',
    'PVH',
    'Logitech',
    'Estee Lauder',
    'IBM',
    'Valio',
    'Salesforce',
    'Sylvamo',
    'Twin Disc',
    'CME Group',
    'CCC',
    'Gestamp',
    'Arla',
    'Uniper SE',
    'Unilever',
    'Procter & Gamble',
    'J. Neves & Fihos (JNF)',
    'Nasdaq',
    'WeWork',
    'Shell',
    'Grammarly',
    'Knight Frank',
    'Booking',
    'Etsy',
    'Arendt & Medernach',
    'Ceratizit',
    'Ferrari',
    'Adidas',
    'Payoneer',
    'Canadian Tire',
    'JCB',
    'Rolls Royce',
    'Universal',
    'Discover',
    'Ricoh',
    'Lumen',
    "McDonald's",
    'Swatch',
    "L'Oreal",
    'Nvidia',
    'Richemont',
    'Nissan',
    'Cleary Gottlieb',
    'Johnson Controls',
    'M&G',
    'Fieldfisher',
]
